import { createRequire } from "node:module";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import assert from "node:assert/strict";
import { setTimeout as delay } from "node:timers/promises";

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PANEL_PLAYWRIGHT_MODULE ?? "playwright");
const output = process.env.PANEL_QA_OUTPUT ?? path.join(tmpdir(), "personal-hub-panel-qa");
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: "chrome", headless: true });
const errors = [];
const check = async (condition, message) => { assert(await condition(), message); };
const until = async (condition, message) => {
  for (let index = 0; index < 100; index++) { if (await condition()) return; await delay(30); }
  throw new Error(message);
};
try {
  const page = await browser.newPage({ viewport: { width: 1496, height: 1151 }, deviceScaleFactor: 1 });
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("http://127.0.0.1:4175/");
  await check(() => page.locator("#sidebar-icon").evaluate((node) => node.complete && node.naturalWidth === 48), "宿主图标资源未成功解码");
  const panel = page.frameLocator("#panel");
  await panel.getByRole("button", { name: "打开：铅酸电池稿件：讨论部分修订", exact: true }).waitFor();
  await panel.getByRole("heading", { name: "本轮更新", exact: true }).waitFor();
  await panel.getByRole("navigation").getByRole("button", { name: "待办", exact: true }).click();
  await panel.getByRole("checkbox", { name: "完成待办：核对讨论部分的实验依据", exact: true }).waitFor();
  assert.equal(await panel.locator(".task-row").count(), 3, "待办默认应与网页一致，仅显示未完成且未关联归档条目的三项");
  assert.equal(await panel.getByRole("button", { name: "未完成", exact: true }).getAttribute("aria-pressed"), "true");
  await panel.getByRole("button", { name: "全部", exact: true }).click();
  await panel.getByText("已完成事项 1", { exact: true }).waitFor();
  assert.equal(await panel.locator(".task-row").count(), 16, "全部状态仍应排除归档关联待办");
  await panel.getByRole("button", { name: "已完成", exact: true }).click();
  await until(() => panel.locator(".task-row").count().then((count) => count === 13), "已完成筛选失败");
  await panel.getByRole("button", { name: "未完成", exact: true }).click();
  await panel.getByRole("combobox", { name: "待办来源筛选" }).selectOption("manual");
  await panel.getByRole("checkbox", { name: "完成待办：整理参考文献", exact: true }).waitFor();
  assert.equal(await panel.locator(".task-row").count(), 1, "待办来源过滤失败");
  await panel.getByRole("combobox", { name: "待办来源筛选" }).selectOption("all");
  await panel.getByRole("checkbox", { name: "完成待办：核对讨论部分的实验依据", exact: true }).waitFor();
  await panel.getByRole("searchbox", { name: "搜索待办" }).fill("参考文献");
  assert.equal(await panel.locator(".task-row").count(), 1, "待办搜索失败");
  await panel.getByRole("searchbox", { name: "搜索待办" }).fill("");
  await page.locator("#panel").screenshot({ path: `${output}/tasks.jpg`, type: "jpeg", quality: 92 });
  await panel.getByRole("navigation").getByRole("button", { name: "收件箱", exact: true }).click();
  await panel.getByRole("heading", { name: "本轮更新", exact: true }).waitFor();
  await page.locator("#panel").screenshot({ path: `${output}/wide.jpg`, type: "jpeg", quality: 92 });
  await check(() => panel.locator("html").evaluate((node) => node.scrollWidth <= node.clientWidth), "宽屏溢出");
  await panel.getByRole("button", { name: "加载更多记录", exact: true }).click();
  await panel.getByRole("button", { name: "打开：研究记录 57", exact: true }).waitFor({ state: "attached" });
  await check(() => panel.getByRole("button", { name: "加载更多记录", exact: true }).count().then((count) => count === 0), "末页游标错误");
  const selection = panel.getByRole("checkbox", { name: "选择：铅酸电池稿件：讨论部分修订", exact: true });
  await selection.click(); await until(() => selection.isChecked(), "选中快照未完成读取");
  await panel.getByRole("button", { name: "带入聊天", exact: true }).click();
  await panel.getByRole("button", { name: "附到聊天", exact: true }).click();
  await page.getByText("聊天引用 1 条", { exact: true }).waitFor();
  assert.equal(await page.getByRole("textbox", { name: "聊天草稿" }).inputValue(), "保留的聊天草稿");
  await panel.getByRole("combobox", { name: "历史版本" }).selectOption("1");
  await panel.getByRole("heading", { name: "初始记录", exact: true }).waitFor();
  await panel.getByRole("button", { name: "引用当前版本", exact: true }).click();
  await until(() => panel.getByRole("button", { name: "引用当前版本", exact: true }).count().then((count) => count === 0), "引用版本未更新");
  await panel.getByRole("button", { name: "带入聊天", exact: true }).click();
  await panel.getByRole("button", { name: "附到聊天", exact: true }).click();
  await until(async () => JSON.parse(await page.locator("#context-text").textContent()).structuredContent.records[0]?.version === 1, "附件版本错误");
  await page.getByRole("button", { name: "移除引用", exact: true }).click();
  await until(() => panel.getByRole("region", { name: "已选引用" }).innerText().then((text) => text.includes("已选 0 条")), "未同步宿主引用移除");
  await panel.getByRole("button", { name: "打开：研究记录 02", exact: true }).click();
  await panel.getByRole("heading", { name: "研究记录 02", exact: true }).waitFor();
  await panel.getByRole("button", { name: "打开：铅酸电池稿件：讨论部分修订", exact: true }).click();
  await panel.getByRole("heading", { name: "本轮更新", exact: true }).waitFor();
  await panel.getByRole("button", { name: "创建待办", exact: true }).click();
  await panel.getByRole("textbox", { name: "待办标题" }).fill("补充局限性说明");
  await panel.getByRole("dialog").getByRole("button", { name: "创建待办", exact: true }).click();
  await panel.getByRole("dialog").waitFor({ state: "hidden" });
  await panel.getByRole("navigation").getByRole("button", { name: "待办", exact: true }).click();
  const task = panel.getByRole("checkbox", { name: "完成待办：补充局限性说明", exact: true });
  await task.waitFor();
  await check(() => task.locator("..").getByText("论文进展", { exact: true }).isVisible(), "关联待办丢失来源");
  await task.click(); await task.waitFor({ state: "detached" });
  await panel.getByRole("button", { name: "已完成", exact: true }).click(); await task.waitFor();
  assert(await task.isChecked(), "已完成的待办未出现在已完成筛选中");
  await panel.getByRole("navigation").getByRole("button", { name: "收件箱", exact: true }).click();
  await panel.getByRole("button", { name: "打开：铅酸电池稿件：讨论部分修订", exact: true }).click();
  await panel.getByRole("heading", { name: "本轮更新", exact: true }).waitFor();
  await panel.getByRole("region", { name: "条目详情" }).getByRole("button", { name: "归档", exact: true }).click();
  await until(() => panel.getByRole("button", { name: "打开：铅酸电池稿件：讨论部分修订", exact: true }).count().then((count) => count === 0), "归档未移除条目");
  await panel.getByRole("navigation").getByRole("button", { name: "归档", exact: true }).click();
  await panel.getByRole("heading", { name: "本轮更新", exact: true }).waitFor();
  await panel.getByRole("button", { name: "取消归档", exact: true }).click();
  await until(() => panel.getByRole("button", { name: "打开：铅酸电池稿件：讨论部分修订", exact: true }).count().then((count) => count === 0), "归档恢复失败");
  await panel.getByRole("navigation").getByRole("button", { name: "来源", exact: true }).click();
  await panel.getByRole("button", { name: "查看来源：论文进展", exact: true }).click();
  await panel.getByRole("combobox", { name: "展示方式" }).selectOption("list");
  await panel.getByRole("button", { name: "展开：铅酸电池稿件：讨论部分修订", exact: true }).click();
  await panel.getByRole("heading", { name: "本轮更新", exact: true }).waitFor();
  await panel.getByRole("combobox", { name: "展示方式" }).selectOption("feed");
  await panel.getByRole("heading", { name: "本轮更新", exact: true }).waitFor();
  await panel.getByRole("combobox", { name: "展示方式" }).selectOption("report");
  await panel.getByRole("heading", { name: "研究记录 02", exact: true }).waitFor();
  await panel.getByRole("navigation").getByRole("button", { name: "收件箱", exact: true }).click();
  await page.setViewportSize({ width: 620, height: 980 });
  await page.reload();
  await panel.getByRole("button", { name: "打开：铅酸电池稿件：讨论部分修订", exact: true }).waitFor();
  await page.locator("#panel").screenshot({ path: `${output}/panel.jpg`, type: "jpeg", quality: 92 });
  await panel.getByRole("button", { name: "打开：铅酸电池稿件：讨论部分修订", exact: true }).click();
  await panel.getByRole("heading", { name: "本轮更新", exact: true }).waitFor();
  await page.locator("#panel").screenshot({ path: `${output}/detail.jpg`, type: "jpeg", quality: 92 });
  await check(() => panel.locator("html").evaluate((node) => node.scrollWidth <= node.clientWidth), "窄面板溢出");
  await page.setViewportSize({ width: 390, height: 944 });
  await panel.getByRole("button", { name: "返回列表", exact: true }).click();
  await page.locator("#panel").screenshot({ path: `${output}/mobile.jpg`, type: "jpeg", quality: 92 });
  await check(() => panel.locator("html").evaluate((node) => node.scrollWidth <= node.clientWidth), "手机视口溢出");
  await page.setViewportSize({ width: 620, height: 980 });
  await page.goto("http://127.0.0.1:4175/?theme=dark");
  await panel.getByRole("button", { name: "打开：铅酸电池稿件：讨论部分修订", exact: true }).waitFor();
  await page.locator("#panel").screenshot({ path: `${output}/dark.jpg`, type: "jpeg", quality: 92 });
  await page.setViewportSize({ width: 1920, height: 1080 });
  const hovered = panel.locator(".entry-row").nth(1);
  await hovered.hover();
  const colors = await hovered.evaluate((row) => ({ background: row.ownerDocument.defaultView.getComputedStyle(row).backgroundColor,
    text: row.ownerDocument.defaultView.getComputedStyle(row.querySelector("strong")).color, meta: row.ownerDocument.defaultView.getComputedStyle(row.querySelector(".row-meta")).color }));
  const luminance = (color) => {
    const channels = color.match(/\d+/g).slice(0, 3).map(Number).map((value) => value / 255).map((value) => value <= .04045 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4);
    return .2126 * channels[0] + .7152 * channels[1] + .0722 * channels[2];
  };
  const contrast = (foreground) => (Math.max(luminance(foreground), luminance(colors.background)) + .05) / (Math.min(luminance(foreground), luminance(colors.background)) + .05);
  assert(contrast(colors.text) >= 4.5 && contrast(colors.meta) >= 4.5, "夜间悬停文字对比度不足");
  await check(() => panel.locator(".list-pane").evaluate((node) => node.getBoundingClientRect().width <= 441), "宽屏列表按百分比过度扩张");
  await check(() => panel.locator(".hub-app").evaluate((node) => Math.abs(node.getBoundingClientRect().height - node.ownerDocument.defaultView.innerHeight) < 2), "面板未填满宿主高度");
  await page.locator("#panel").screenshot({ path: `${output}/dark-hover.jpg`, type: "jpeg", quality: 92 });
  await page.setViewportSize({ width: 620, height: 460 });
  await until(() => panel.locator(".hub-app").evaluate((node) => Math.abs(node.getBoundingClientRect().height - node.ownerDocument.defaultView.innerHeight) < 2 && node.ownerDocument.documentElement.scrollHeight === node.ownerDocument.documentElement.clientHeight), "短面板最小高度导致裁切");
  await until(() => panel.getByRole("region", { name: "已选引用" }).evaluate((node) => node.getBoundingClientRect().bottom <= node.ownerDocument.defaultView.innerHeight), "短面板底部引用托盘被裁切");
  await page.locator("#panel").screenshot({ path: `${output}/short.jpg`, type: "jpeg", quality: 92 });
  await page.setViewportSize({ width: 620, height: 980 });
  await page.getByRole("button", { name: "测试安全留白", exact: true }).click();
  await until(() => panel.getByRole("region", { name: "已选引用" }).evaluate((node) => node.getBoundingClientRect().bottom <= node.ownerDocument.defaultView.innerHeight - 64), "宿主底部安全区域未保留");
  await page.locator("#panel").screenshot({ path: `${output}/safe-area.jpg`, type: "jpeg", quality: 92 });
  await page.setViewportSize({ width: 1496, height: 1151 });
  // Failures must leave the task list usable and restore the button without retrying.
  await page.goto("http://127.0.0.1:4175/?fail_clear=1&theme=dark");
  await panel.getByRole("navigation").getByRole("button", { name: "待办", exact: true }).click();
  await panel.getByRole("button", { name: "已完成", exact: true }).click();
  await until(() => panel.locator(".task-row").count().then((count) => count === 13), "失败测试未加载已完成待办");
  await panel.getByRole("button", { name: "清除已完成", exact: true }).click();
  await panel.getByRole("dialog").getByText(/包括归档关联项/).waitFor();
  await panel.getByRole("button", { name: "确认清除", exact: true }).click();
  await panel.getByRole("alert").getByText("暂时无法清除已完成待办，请稍后再试").waitFor();
  assert.equal(await panel.locator(".task-row").count(), 13, "清除失败不应移除现有任务");
  assert(await panel.getByRole("button", { name: "清除已完成", exact: true }).isEnabled(), "失败后按钮未恢复");
  const failedCalls = await page.locator("#test-status").textContent(); await delay(150);
  assert.equal(await page.locator("#test-status").textContent(), failedCalls, "清除失败发生自动重试");
  await page.locator("#panel").screenshot({ path: `${output}/clear-failure.jpg`, type: "jpeg", quality: 92 });
  await panel.getByRole("navigation").getByRole("button", { name: "收件箱", exact: true }).click();
  await panel.getByRole("heading", { name: "本轮更新", exact: true }).waitFor();
  await page.goto("http://127.0.0.1:4175/?theme=dark");
  await panel.getByRole("navigation").getByRole("button", { name: "待办", exact: true }).click();
  await panel.getByRole("checkbox", { name: "完成待办：核对讨论部分的实验依据", exact: true }).waitFor();
  const callsBeforeConfirm = await page.locator("#test-status").textContent();
  await panel.getByRole("button", { name: "清除已完成", exact: true }).click();
  await panel.getByRole("dialog").getByText(/包括归档关联项/).waitFor();
  assert.equal(await page.locator("#test-status").textContent(), callsBeforeConfirm, "打开确认弹窗不应查询数据库");
  await page.locator("#panel").screenshot({ path: `${output}/clear-confirm.jpg`, type: "jpeg", quality: 92 });
  await panel.getByRole("button", { name: "取消", exact: true }).click();
  await panel.getByRole("button", { name: "清除已完成", exact: true }).click();
  await panel.getByRole("button", { name: "确认清除", exact: true }).click();
  await panel.getByRole("status").getByText("已清除 13 项已完成待办").waitFor();
  await until(() => panel.locator(".task-row").count().then((count) => count === 3), "成功后未保留三项未完成待办");
  await panel.getByRole("button", { name: "已完成", exact: true }).click();
  await until(() => panel.locator(".task-row").count().then((count) => count === 0), "成功后已完成待办未清空");
  await page.goto("http://127.0.0.1:4175/?role=reader");
  await panel.getByRole("heading", { name: "本轮更新", exact: true }).waitFor();
  assert.equal(await panel.getByRole("button", { name: "创建待办", exact: true }).count(), 0);
  assert.equal(await panel.getByRole("button", { name: "标记已读", exact: true }).count(), 0);
  await panel.getByRole("navigation").getByRole("button", { name: "待办", exact: true }).click();
  const readonlyTask = panel.getByRole("checkbox", { name: "完成待办：核对讨论部分的实验依据", exact: true }); await readonlyTask.waitFor(); assert(await readonlyTask.isDisabled());
  assert.equal(await panel.getByRole("button", { name: "清除已完成", exact: true }).count(), 0);
  assert.deepEqual(errors, []);
  console.log("Panel QA passed: completed cleanup confirmation without database calls/cancel/success/write failure/button recovery/no retries; website task parity, task/source filters, search, pagination, immutable versions, model context, draft preservation, context removal, linked task source, archive recovery, feed/list/report, 1920/1496/620/390px, short panels, dark hover contrast, reader permissions; page errors = 0.");
} finally { await browser.close(); }
